on:
  schedule:
    - cron: '0 */12 * * *' # every 12 hours
  push:
    branches:
      - main
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Profile Readme Stats
      uses: teoxoy/profile-readme-stats@v2
      with:
        token: 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
    - name: Update README.md
      run: |
        git add .
        git commit -m "Update README"
        git push
        fi
